public class JavaOutput{
	
public static void main(String[] args){
	//Using the println method
  System.out.println("Hello World, this is my first Java program");
  System.out.println("Learning Java Is Fun");
  
  
  
  
  
   //Using the print method
   System.out.print("Do You Love \"Learning Java\"? ");
   System.out.print("Yes I Love Learning Java\n ");
  
   
   
   //Using the print f
   System.out.printf("My name is David Dennis, I am %d Years Old %n",17);
  }
	
	
	
	
	
	
	
}